#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const checks = [];
const add = (name, ok, detail='') => checks.push({ name, ok, detail });

const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
const cap = JSON.parse(fs.readFileSync(path.join(root, 'capacitor.config.json'), 'utf8'));
add('App ID', cap.appId === 'com.bill4pe.app', cap.appId);
add('App name', cap.appName === 'BILL4PE', cap.appName);
add('Camera plugin', !!pkg.dependencies['@capacitor/camera']);
add('Geolocation plugin', !!pkg.dependencies['@capacitor/geolocation']);
add('Status bar plugin', !!pkg.dependencies['@capacitor/status-bar']);
add('Android project', fs.existsSync(path.join(root, 'android')), 'generated by npm run mobile:prepare');
add('iOS project', fs.existsSync(path.join(root, 'ios')), 'generated by npm run mobile:prepare');
add('1024 icon', fs.existsSync(path.join(root, 'assets/icon.png')));

let backend = '';
const env = path.join(root, '.env');
if (fs.existsSync(env)) {
  const m = fs.readFileSync(env, 'utf8').match(/^REACT_APP_BACKEND_URL\s*=\s*["']?([^\r\n"']+)/m);
  backend = (m && m[1] || '').trim();
}
add('Backend URL configured', /^https:\/\//i.test(backend), backend || 'missing');

console.log('\nBILL4PE Mobile Doctor');
for (const c of checks) console.log(`${c.ok ? 'OK ' : '!! '} ${c.name}${c.detail ? ` — ${c.detail}` : ''}`);
const hardFail = checks.some(c => ['App ID','App name','Camera plugin','Geolocation plugin','Status bar plugin'].includes(c.name) && !c.ok);
if (hardFail) process.exit(1);
